data:
  train_dir: '/scratch/c.c1767198/data/fishDatabase/stratified_saprolegnia/train'
  val_dir: '/scratch/c.c1767198/data/fishDatabase/stratified_saprolegnia/val'
  test_dir: '/scratch/c.c1767198/data/fishDatabase/stratified_saprolegnia/test'
  batch_size: 32
  augmentation:
    rotation_range: 0.2
    zoom_range: 0.2
    contrast_range: 0.2
    brightness_range: 0.2

models:
  MobileNetV3:
    img_size: 224
  EfficientNetV2B0:
    img_size: 224
  EfficientNetV2S:
    img_size: 300
  ResNet50:
    img_size: 224

training:
  epochs: 50
  learning_rate: 0.001
  focal_loss_gamma: 2.0

sampling:
  method: 'mild_square_root'
  power: 0.3