data:
  train_dir: '/scratch/c.c1767198/data/fishDatabase/stratified_saprolegnia/train'
  val_dir: '/scratch/c.c1767198/data/fishDatabase/stratified_saprolegnia/val'
  test_dir: '/scratch/c.c1767198/data/fishDatabase/stratified_saprolegnia/test'
  batch_size: 32
  augmentation_magnitude: 0.6  # Adjust this value as needed

models:
  MobileNetV3:
    img_size: 224
  EfficientNetV2B0:
    img_size: 224
  EfficientNetV2S:
    img_size: 300
  ResNet50:
    img_size: 224

training:
  epochs: 25
  learning_rate: 0.001
  focal_loss_gamma: 2.0
sampling:
  method: minority_oversampling
  power: 0.3
