data:
  output_dir: '/scratch/c.c1767198/output/sapro_classification_comparison/final_salmo_onco_user_grouped'
  train_dir: '/scratch/c.c1767198/data/fishDatabase/final_splits/salmo_onco_nfold/train'
  #test_dir: '/scratch/c.c1767198/data/fishDatabase/final_splits/salmo_usergroup_nfold/test'
  batch_size: 32
  augmentation_magnitude: 0.6  # Adjust this value as needed
  num_classes: 2
  class_names: ['healthy','sapro']
  #weights_path: '/scratch/c.c1767198/output/V2M_wildlife_no_possum.weights.h5'
  weights_path: null
  metadata_path: "/scratch/c.c1767198/data/fishDatabase/full_combined_metadata_scientific_nodupes.csv"
  group_column: "user"
  stratify_columns: 
    - "source"
    - "scientific_name_fixed"

models:
  MobileNetV3S:
    img_size: 224
    num_dense_layers: 128
    unfreeze_layers: 52
  EfficientNetV2B0:
    img_size: 224
    num_dense_layers: 256
    unfreeze_layers: 198
  EfficientNetV2S:
    img_size: 300
    num_dense_layers: 512
    unfreeze_layers: 363
  EfficientNetV2M:
    img_size: 384
    num_dense_layers: 512
    unfreeze_layers: 348
  ResNet50:
    img_size: 224
    num_dense_layers: 128
    unfreeze_layers: 98

sampling:
  use_weights: false  # Set this to false to disable weights
  method: mild_square_root
  power: 0.3
  #samples_per_class: 400  # Optional: specify the number of samples per class, or omit to use the minimum class size


training:
  initial_epochs: 20
  fine_tuning_epochs: 40
  learning_rate: 0.001
  fine_tuning_lr: 0.00001
  focal_loss_gamma: 2.0
  new_dataset_per_epoch: false  # Set to true to enable new dataset creation per epoch
  early_stopping_patience: 10  # Add this line, adjust the value as needed
  use_groups: true  # Set to true to enable grouping by user
  n_folds: 5
  use_oversampling: true  # Enable oversampling
  sampling_strategy: "match_majority"  # Options: "threshold", "match_majority", "progressive"
  threshold_ratio: 0.5  # Only used if strategy is "threshold"